print("questionnaire")
first_name = input("first name:")
last_name = input("last_name:")
date_year = input("date year:")
gender = input("gender:")
mobile_number = input("mobile number:")
do_you_like_the_course = input("do you like the course:")
print("full name:", first_name, last_name)
print("age", 2023 - int(date_year))
print("gender:", gender)
print("mobile number:",mobile_number)
print("do you like the course:",do_you_like_the_course)
